//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M64RPFW.Views.Avalonia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M64RPFW.Views.Avalonia.Resources.Resources.de-DE", typeof(Resources_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchsuchen....
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rom schließen.
        /// </summary>
        internal static string CloseRom {
            get {
                return ResourceManager.GetString("CloseRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kern.
        /// </summary>
        internal static string Core {
            get {
                return ResourceManager.GetString("Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählter Slot.
        /// </summary>
        internal static string CurrentSlot {
            get {
                return ResourceManager.GetString("CurrentSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion Pak-Speicher deaktivieren.
        /// </summary>
        internal static string DisableExpansionPakMemory {
            get {
                return ResourceManager.GetString("DisableExpansionPakMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schreibschutz.
        /// </summary>
        internal static string DisableWrites {
            get {
                return ResourceManager.GetString("DisableWrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulator.
        /// </summary>
        internal static string Emulator {
            get {
                return ResourceManager.GetString("Emulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild fortschreiten.
        /// </summary>
        internal static string FrameAdvance {
            get {
                return ResourceManager.GetString("FrameAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabe.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählten Slot laden.
        /// </summary>
        internal static string LoadCurrentSlot {
            get {
                return ResourceManager.GetString("LoadCurrentSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von Datei laden....
        /// </summary>
        internal static string LoadFromFile {
            get {
                return ResourceManager.GetString("LoadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State laden.
        /// </summary>
        internal static string LoadState {
            get {
                return ResourceManager.GetString("LoadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufnahme.
        /// </summary>
        internal static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rom öffnen....
        /// </summary>
        internal static string OpenRom {
            get {
                return ResourceManager.GetString("OpenRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausieren/Fortsetzen.
        /// </summary>
        internal static string PauseOrResume {
            get {
                return ResourceManager.GetString("PauseOrResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupt-Timings randomisieren.
        /// </summary>
        internal static string RandomizeInterruptTimings {
            get {
                return ResourceManager.GetString("RandomizeInterruptTimings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Roms.
        /// </summary>
        internal static string RecentRoms {
            get {
                return ResourceManager.GetString("RecentRoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerecording.
        /// </summary>
        internal static string Rerecording {
            get {
                return ResourceManager.GetString("Rerecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rom neu laden.
        /// </summary>
        internal static string ResetRom {
            get {
                return ResourceManager.GetString("ResetRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufnahme neu starten.
        /// </summary>
        internal static string RestartMovie {
            get {
                return ResourceManager.GetString("RestartMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSP.
        /// </summary>
        internal static string Rsp {
            get {
                return ResourceManager.GetString("Rsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählten Slot speichern.
        /// </summary>
        internal static string SaveCurrentSlot {
            get {
                return ResourceManager.GetString("SaveCurrentSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State speichern.
        /// </summary>
        internal static string SaveState {
            get {
                return ResourceManager.GetString("SaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern unter....
        /// </summary>
        internal static string SaveToFile {
            get {
                return ResourceManager.GetString("SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder starten....
        /// </summary>
        internal static string StartEncoder {
            get {
                return ResourceManager.GetString("StartEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startzustand.
        /// </summary>
        internal static string StartFrom {
            get {
                return ResourceManager.GetString("StartFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabe starten....
        /// </summary>
        internal static string StartPlaying {
            get {
                return ResourceManager.GetString("StartPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufnahme starten....
        /// </summary>
        internal static string StartRecording {
            get {
                return ResourceManager.GetString("StartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder stoppen.
        /// </summary>
        internal static string StopEncoder {
            get {
                return ResourceManager.GetString("StopEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufnahme stoppen....
        /// </summary>
        internal static string StopMovie {
            get {
                return ResourceManager.GetString("StopMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbschema.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schreibschutz umschalten.
        /// </summary>
        internal static string ToggleDisableWrites {
            get {
                return ResourceManager.GetString("ToggleDisableWrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
