//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M64RPFW.Views.Avalonia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M64RPFW.Views.Avalonia.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings....
        /// </summary>
        internal static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M64RPFW.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Rom.
        /// </summary>
        internal static string CloseRom {
            get {
                return ResourceManager.GetString("CloseRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string ConfigKey {
            get {
                return ResourceManager.GetString("ConfigKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ConfigValue {
            get {
                return ResourceManager.GetString("ConfigValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        internal static string Core {
            get {
                return ResourceManager.GetString("Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Section.
        /// </summary>
        internal static string CurrentSection {
            get {
                return ResourceManager.GetString("CurrentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Slot.
        /// </summary>
        internal static string CurrentSlot {
            get {
                return ResourceManager.GetString("CurrentSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Expansion Pak Memory.
        /// </summary>
        internal static string DisableExpansionPakMemory {
            get {
                return ResourceManager.GetString("DisableExpansionPakMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only.
        /// </summary>
        internal static string DisableWrites {
            get {
                return ResourceManager.GetString("DisableWrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulator.
        /// </summary>
        internal static string Emulator {
            get {
                return ResourceManager.GetString("Emulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Advance.
        /// </summary>
        internal static string FrameAdvance {
            get {
                return ResourceManager.GetString("FrameAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Current Slot.
        /// </summary>
        internal static string LoadCurrentSlot {
            get {
                return ResourceManager.GetString("LoadCurrentSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from File....
        /// </summary>
        internal static string LoadFromFile {
            get {
                return ResourceManager.GetString("LoadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load State.
        /// </summary>
        internal static string LoadState {
            get {
                return ResourceManager.GetString("LoadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua.
        /// </summary>
        internal static string Lua {
            get {
                return ResourceManager.GetString("Lua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        internal static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Instance....
        /// </summary>
        internal static string NewLuaInstance {
            get {
                return ResourceManager.GetString("NewLuaInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Rom....
        /// </summary>
        internal static string OpenRom {
            get {
                return ResourceManager.GetString("OpenRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause/Resume.
        /// </summary>
        internal static string PauseOrResume {
            get {
                return ResourceManager.GetString("PauseOrResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize interrupt timings.
        /// </summary>
        internal static string RandomizeInterruptTimings {
            get {
                return ResourceManager.GetString("RandomizeInterruptTimings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Roms.
        /// </summary>
        internal static string RecentRoms {
            get {
                return ResourceManager.GetString("RecentRoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerecording.
        /// </summary>
        internal static string Rerecording {
            get {
                return ResourceManager.GetString("Rerecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Rom.
        /// </summary>
        internal static string ResetRom {
            get {
                return ResourceManager.GetString("ResetRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Movie.
        /// </summary>
        internal static string RestartMovie {
            get {
                return ResourceManager.GetString("RestartMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSP.
        /// </summary>
        internal static string Rsp {
            get {
                return ResourceManager.GetString("Rsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Current Slot.
        /// </summary>
        internal static string SaveCurrentSlot {
            get {
                return ResourceManager.GetString("SaveCurrentSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save State.
        /// </summary>
        internal static string SaveState {
            get {
                return ResourceManager.GetString("SaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to File....
        /// </summary>
        internal static string SaveToFile {
            get {
                return ResourceManager.GetString("SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Encoder....
        /// </summary>
        internal static string StartEncoder {
            get {
                return ResourceManager.GetString("StartEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start from.
        /// </summary>
        internal static string StartFrom {
            get {
                return ResourceManager.GetString("StartFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Playing....
        /// </summary>
        internal static string StartPlaying {
            get {
                return ResourceManager.GetString("StartPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recording....
        /// </summary>
        internal static string StartRecording {
            get {
                return ResourceManager.GetString("StartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Encoder.
        /// </summary>
        internal static string StopEncoder {
            get {
                return ResourceManager.GetString("StopEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Movie.
        /// </summary>
        internal static string StopMovie {
            get {
                return ResourceManager.GetString("StopMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Read-only.
        /// </summary>
        internal static string ToggleDisableWrites {
            get {
                return ResourceManager.GetString("ToggleDisableWrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Height.
        /// </summary>
        internal static string VideoHeight {
            get {
                return ResourceManager.GetString("VideoHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Width.
        /// </summary>
        internal static string VideoWidth {
            get {
                return ResourceManager.GetString("VideoWidth", resourceCulture);
            }
        }
    }
}
