//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M64RPFW.Views.Avalonia.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("M64RPFW.Views.Avalonia.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        internal static string OpenRom {
            get {
                return ResourceManager.GetString("OpenRom", resourceCulture);
            }
        }
        
        internal static string CloseRom {
            get {
                return ResourceManager.GetString("CloseRom", resourceCulture);
            }
        }
        
        internal static string ResetRom {
            get {
                return ResourceManager.GetString("ResetRom", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Emulator {
            get {
                return ResourceManager.GetString("Emulator", resourceCulture);
            }
        }
        
        internal static string PauseOrResume {
            get {
                return ResourceManager.GetString("PauseOrResume", resourceCulture);
            }
        }
        
        internal static string FrameAdvance {
            get {
                return ResourceManager.GetString("FrameAdvance", resourceCulture);
            }
        }
        
        internal static string LoadFromFile {
            get {
                return ResourceManager.GetString("LoadFromFile", resourceCulture);
            }
        }
        
        internal static string SaveToFile {
            get {
                return ResourceManager.GetString("SaveToFile", resourceCulture);
            }
        }
        
        internal static string LoadState {
            get {
                return ResourceManager.GetString("LoadState", resourceCulture);
            }
        }
        
        internal static string SaveState {
            get {
                return ResourceManager.GetString("SaveState", resourceCulture);
            }
        }
        
        internal static string CurrentSlot {
            get {
                return ResourceManager.GetString("CurrentSlot", resourceCulture);
            }
        }
        
        internal static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        internal static string StartPlaying {
            get {
                return ResourceManager.GetString("StartPlaying", resourceCulture);
            }
        }
        
        internal static string StartRecording {
            get {
                return ResourceManager.GetString("StartRecording", resourceCulture);
            }
        }
        
        internal static string StopMovie {
            get {
                return ResourceManager.GetString("StopMovie", resourceCulture);
            }
        }
        
        internal static string RestartMovie {
            get {
                return ResourceManager.GetString("RestartMovie", resourceCulture);
            }
        }
        
        internal static string DisableWrites {
            get {
                return ResourceManager.GetString("DisableWrites", resourceCulture);
            }
        }
        
        internal static string StartEncoder {
            get {
                return ResourceManager.GetString("StartEncoder", resourceCulture);
            }
        }
        
        internal static string StopEncoder {
            get {
                return ResourceManager.GetString("StopEncoder", resourceCulture);
            }
        }
        
        internal static string Core {
            get {
                return ResourceManager.GetString("Core", resourceCulture);
            }
        }
        
        internal static string DisableExpansionPakMemory {
            get {
                return ResourceManager.GetString("DisableExpansionPakMemory", resourceCulture);
            }
        }
        
        internal static string RandomizeInterruptTimings {
            get {
                return ResourceManager.GetString("RandomizeInterruptTimings", resourceCulture);
            }
        }
        
        internal static string LoadCurrentSlot {
            get {
                return ResourceManager.GetString("LoadCurrentSlot", resourceCulture);
            }
        }
        
        internal static string SaveCurrentSlot {
            get {
                return ResourceManager.GetString("SaveCurrentSlot", resourceCulture);
            }
        }
        
        internal static string ToggleDisableWrites {
            get {
                return ResourceManager.GetString("ToggleDisableWrites", resourceCulture);
            }
        }
        
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        internal static string Rsp {
            get {
                return ResourceManager.GetString("Rsp", resourceCulture);
            }
        }
        
        internal static string Rerecording {
            get {
                return ResourceManager.GetString("Rerecording", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string StartFrom {
            get {
                return ResourceManager.GetString("StartFrom", resourceCulture);
            }
        }
        
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        internal static string RecentRoms {
            get {
                return ResourceManager.GetString("RecentRoms", resourceCulture);
            }
        }
        
        internal static string VideoHeight {
            get {
                return ResourceManager.GetString("VideoHeight", resourceCulture);
            }
        }
        
        internal static string VideoWidth {
            get {
                return ResourceManager.GetString("VideoWidth", resourceCulture);
            }
        }
        
        internal static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        internal static string ConfigKey {
            get {
                return ResourceManager.GetString("ConfigKey", resourceCulture);
            }
        }
        
        internal static string ConfigValue {
            get {
                return ResourceManager.GetString("ConfigValue", resourceCulture);
            }
        }
        
        internal static string CurrentSection {
            get {
                return ResourceManager.GetString("CurrentSection", resourceCulture);
            }
        }
        
        internal static string Lua {
            get {
                return ResourceManager.GetString("Lua", resourceCulture);
            }
        }
        
        internal static string NewLuaInstance {
            get {
                return ResourceManager.GetString("NewLuaInstance", resourceCulture);
            }
        }
        
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        internal static string FastForward {
            get {
                return ResourceManager.GetString("FastForward", resourceCulture);
            }
        }
        
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        internal static string RomBrowserRecursive {
            get {
                return ResourceManager.GetString("RomBrowserRecursive", resourceCulture);
            }
        }
        
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        internal static string VSync {
            get {
                return ResourceManager.GetString("VSync", resourceCulture);
            }
        }
        
        internal static string RequiresRestartToApply {
            get {
                return ResourceManager.GetString("RequiresRestartToApply", resourceCulture);
            }
        }
    }
}
