//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M64RPFW.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M64RPFW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M64RPFW.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Endian.
        /// </summary>
        public static string BigEndian {
            get {
                return ResourceManager.GetString("BigEndian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached Interpreter.
        /// </summary>
        public static string CachedInterpreter {
            get {
                return ResourceManager.GetString("CachedInterpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot terminate an inexistent emulator..
        /// </summary>
        public static string CannotStopUnstartedGame {
            get {
                return ResourceManager.GetString("CannotStopUnstartedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close ROM.
        /// </summary>
        public static string CloseROM {
            get {
                return ResourceManager.GetString("CloseROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The core library was not found..
        /// </summary>
        public static string CoreLibraryNotFound {
            get {
                return ResourceManager.GetString("CoreLibraryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string CPU {
            get {
                return ResourceManager.GetString("CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Recompiler.
        /// </summary>
        public static string DynamicRecompiler {
            get {
                return ResourceManager.GetString("DynamicRecompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Advance.
        /// </summary>
        public static string FrameAdvance {
            get {
                return ResourceManager.GetString("FrameAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUI.
        /// </summary>
        public static string GUI {
            get {
                return ResourceManager.GetString("GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect.
        /// </summary>
        public static string Inspect {
            get {
                return ResourceManager.GetString("Inspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Name.
        /// </summary>
        public static string InternalName {
            get {
                return ResourceManager.GetString("InternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided ROM is invalid.
        /// </summary>
        public static string InvalidROMError {
            get {
                return ResourceManager.GetString("InvalidROMError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load ROM.
        /// </summary>
        public static string LoadROM {
            get {
                return ResourceManager.GetString("LoadROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Format.
        /// </summary>
        public static string MediaFormat {
            get {
                return ResourceManager.GetString("MediaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mupen64Plus.
        /// </summary>
        public static string Mupen64Plus {
            get {
                return ResourceManager.GetString("Mupen64Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following plugins are missing: {0}..
        /// </summary>
        public static string PluginNotFoundSeries {
            get {
                return ResourceManager.GetString("PluginNotFoundSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} plugin library was not found..
        /// </summary>
        public static string PluginNotFoundTemplate {
            get {
                return ResourceManager.GetString("PluginNotFoundTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin settings.
        /// </summary>
        public static string PluginSettings {
            get {
                return ResourceManager.GetString("PluginSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary CRC.
        /// </summary>
        public static string PrimaryCRC {
            get {
                return ResourceManager.GetString("PrimaryCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program settings.
        /// </summary>
        public static string ProgramSettings {
            get {
                return ResourceManager.GetString("ProgramSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pure Interpreter.
        /// </summary>
        public static string PureInterpreter {
            get {
                return ResourceManager.GetString("PureInterpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Data.
        /// </summary>
        public static string RawData {
            get {
                return ResourceManager.GetString("RawData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset ROM.
        /// </summary>
        public static string ResetROM {
            get {
                return ResourceManager.GetString("ResetROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ROM does not exist.
        /// </summary>
        public static string ROMInexistent {
            get {
                return ResourceManager.GetString("ROMInexistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSP.
        /// </summary>
        public static string RSP {
            get {
                return ResourceManager.GetString("RSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary CRC.
        /// </summary>
        public static string SecondaryCRC {
            get {
                return ResourceManager.GetString("SecondaryCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Statusbar.
        /// </summary>
        public static string ShowStatusbar {
            get {
                return ResourceManager.GetString("ShowStatusbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Toolbar.
        /// </summary>
        public static string ShowToolbar {
            get {
                return ResourceManager.GetString("ShowToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t host multiple emulators simultaneously..
        /// </summary>
        public static string SingularGameLimit {
            get {
                return ResourceManager.GetString("SingularGameLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR LOADING TEXT.
        /// </summary>
        public static string SPECIAL_FallbackLocalizationText {
            get {
                return ResourceManager.GetString("SPECIAL_FallbackLocalizationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
