# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore

    #- name: Setup MSBuild
    #  uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
        
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
        
    - name: Dotnet Build
      run: |
          dotnet build "M64RPFW.Views.Avalonia\M64RPFW.Views.Avalonia.csproj" /p:platform="AnyCPU" /p:configuration="Release"
          
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
          name: M64RPFW.Views.Avalonia .NET 7 Release
          path: 'M64RPFW.Views.Avalonia/bin/Release/net7.0'
